# Generated by Django 5.2.4 on 2025-07-29 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('ubicacion', models.CharField(max_length=100)),
                ('tipo', models.CharField(default='presencial', max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['fecha', 'hora'],
            },
        ),
    ]
