# Generated by Django 5.2.4 on 2025-07-27 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_evento'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroEventos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('fecha', models.DateTimeField()),
                ('ubicacion', models.CharField(max_length=255)),
                ('organizador', models.CharField(max_length=100)),
                ('descripcion', models.TextField(null=True, verbose_name='Descripción')),
            ],
        ),
        migrations.DeleteModel(
            name='Evento',
        ),
        migrations.DeleteModel(
            name='project',
        ),
    ]
