# Generated by Django 5.2.4 on 2025-07-28 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_registroeventos_delete_evento_delete_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('ubicacion', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('presencial', 'Presencial'), ('virtual', 'Virtual')], max_length=20)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='RegistroEventos',
        ),
    ]
