name: Django CI

on:
  push:
    branches: [ main, develop ] # Ejecuta el workflow en cada push a estas ramas
  pull_request:
    branches: [ main, develop ] # Ejecuta el workflow en cada pull request a estas ramas

jobs:
  build:
    runs-on: ubuntu-latest # Elige el sistema operativo para ejecutar las acciones

    steps:
    # --- INICIO DE LA CORRECCIÓN ---

    # Paso 1: Clonar el repositorio
    - uses: actions/checkout@v4 # Este es el primer paso, sangrado con dos espacios desde 'steps:' y con guion (-)

    # Paso 2: Configurar Python
    - name: Set up Python # Cada paso de la lista debe iniciar con un guion (-)
      uses: actions/setup-python@v5
      with:
        python-version: '3.13.5' # O la versión de Python que uses en tu proyecto

    # Paso 3: Instalar dependencias
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt # Asegúrate de tener un archivo requirements.txt

    # Paso 4: Ejecutar pruebasss
    - name: Run tests
      run: |
        python manage.py test # Ejecuta las pruebas de Django

    # --- FIN DE LA CORRECCIÓN ---- 